---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio
  namespace: portfolio
  annotations:
     cert-manager.io/cluster-issuer: letsencrypt-dns
     kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  tls: 
    - hosts: 
        - "portfolio.ejirolaureld.me"
      secretName: wildcard-cert-f8f62-vb947
  rules:
    - host: "portfolio.ejirolaureld.me"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio
                port:
                  number: 80
