---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-issuer-secret
  namespace: kube-system
data:
  secret-access-key: MTQzWGpCdVpmaXhsbTBIcDIyOXhtUVRLOHFuZ3pKNXFLOXhBb1JEdw==
type: Opaque
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: lets-encrypt-issuer-dev
spec:
  acme:
    dns01:
      providers:
      - name: route53
        route53:
          accessKeyID: QUtJQVkyQTZGWTdaMjNMT1lQRk8
          hostedZoneID: WjA4NTQ3NDVTNFNTR05WNE05TzM=
          region: us-east-1
          secretAccessKeySecretRef:
            name: cluster-issuer-secret
            key: MTQzWGpCdVpmaXhsbTBIcDIyOXhtUVRLOHFuZ3pKNXFLOXhBb1JEdw==
    email: ZGFmZWxhdXJlbGVAZ21haWwuY29t
    privateKeySecretRef:
      name: lets-encrypt-issuer-dev
    server: https://acme-staging-v02.api.letsencrypt.org/directory
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: lets-encrypt-issuer-prod
spec:
  acme:
    dns01:
      providers:
      - name: route53
        route53:
          accessKeyID: QUtJQVkyQTZGWTdaMjNMT1lQRk8
          hostedZoneID: WjA4NTQ3NDVTNFNTR05WNE05TzM=
          region: us-east-1
          secretAccessKeySecretRef:
            name: cluster-issuer-secret
            key: secret-access-key
    email: ZGFmZWxhdXJlbGVAZ21haWwuY29t
    privateKeySecretRef:
      name: lets-encrypt-issuer-prod
    server: https://acme-v02.api.letsencrypt.org/directory
