---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: cert-manager
spec:
  dnsNames:
  - '*.ejirolaureld.live'
  issuerRef:
    name: letsencrypt-dns      
    kind: ClusterIssuer
  secretName: "wildcard-cert"
  commonName: "*.ejirolaureld.me"
