---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-issuer-secret
  namespace: kube-system
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "ZGFmZWxhdXJlbGVAZ21haWwuY29t"
    privateKeySecretRef:
      name: wildcard-cert-bkcvg
    solvers:            
      - dns01: 
          route53:
            accessKeyID: "QUtJQVkyQTZGWTdaMjNMT1lQRk8"
            hostedZoneID: "WjA4NTQ3NDVTNFNTR05WNE05TzM="
            region: us-east-1
            secretAccessKeySecretRef:
              name: cluster-issuer-secret
              key: "MTQzWGpCdVpmaXhsbTBIcDIyOXhtUVRLOHFuZ3pKNXFLOXhBb1JEdw=="


  #---
  #apiVersion: cert-manager.io/v1
  #kind: ClusterIssuer
  #metadata:
  # name: letsencrypt-dns
  #spec:
  # acme:
  #  dns01:
  #   providers:
  #   - name: route53
  #     route53:
  #       accessKeyID: QUtJQVkyQTZGWTdaMjNMT1lQRk8
  #       hostedZoneID: WjA4NTQ3NDVTNFNTR05WNE05TzM=
  #       region: us-east-1
  #       secretAccessKeySecretRef:
  #         name: cluster-issuer-secret
  #         key: secret-access-key
  # email: ZGFmZWxhdXJlbGVAZ21haWwuY29t
  # privateKeySecretRef:
  #   name: letsencrypt-dns
  # server: https://acme-v02.api.letsencrypt.org/directory
