---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-issuer-secret
  namespace: kube-system
  secret-access-key: MTQzWGpCdVpmaXhsbTBIcDIyOXhtUVRLOHFuZ3pKNXFLOXhBb1JEdw==
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
   server: https://acme-v02.api.letsencrypt.org/directory
      solvers:            
      - dns01: 
        route53:
          accessKeyID: QUtJQVkyQTZGWTdaMjNMT1lQRk8
          hostedZoneID: WjA4NTQ3NDVTNFNTR05WNE05TzM=
          region: us-east-1
          secretAccessKeySecretRef:
            name: cluster-issuer-secret
            key: MTQzWGpCdVpmaXhsbTBIcDIyOXhtUVRLOHFuZ3pKNXFLOXhBb1JEdw==
    email: ZGFmZWxhdXJlbGVAZ21haWwuY29t
    privateKeySecretRef:
      name: lets-encrypt-issuer-dev
    server: https://acme-v02.api.letsencrypt.org/directory
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: kube-system
spec:
  dnsNames:
  - '*.ejirolaureld.me'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns
  acme:
    config:
    - dns01:
        provider: route53
      domains:
      - '*.ejirolaureld.me'
  secretName: wildcard-cert


  #---
  #apiVersion: cert-manager.io/v1
  #kind: ClusterIssuer
  #metadata:
  # name: letsencrypt-dns
  #spec:
  # acme:
  #  dns01:
  #   providers:
  #   - name: route53
  #     route53:
  #       accessKeyID: QUtJQVkyQTZGWTdaMjNMT1lQRk8
  #       hostedZoneID: WjA4NTQ3NDVTNFNTR05WNE05TzM=
  #       region: us-east-1
  #       secretAccessKeySecretRef:
  #         name: cluster-issuer-secret
  #         key: secret-access-key
  # email: ZGFmZWxhdXJlbGVAZ21haWwuY29t
  # privateKeySecretRef:
  #   name: letsencrypt-dns
  # server: https://acme-v02.api.letsencrypt.org/directory
